{"nbformat":4,"nbformat_minor":4,"metadata":{"notebookId":"44647469-475e-4765-9862-ced5394c8bba","language_info":{"pygments_lexer":"ipython3","file_extension":".py","version":"3.7.7","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"name":"python","nbconvert_exporter":"python"},"kernelspec":{"name":"python3","display_name":"Yandex DataSphere Kernel","language":"python"}},"cells":[{"cell_type":"code","source":"# %pip install --upgrade wget\n# %pip install requests --upgrade","metadata":{"cellId":"kricpxcqbjdi865iqjudj8","trusted":true},"outputs":[{"output_type":"stream","name":"stdout","text":"\u001B[33mWARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.\u001B[0m\nCollecting requests\n  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)\n\u001B[K     |████████████████████████████████| 61 kB 1.1 MB/s \n\u001B[?25hCollecting certifi>=2017.4.17\n  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)\n\u001B[K     |████████████████████████████████| 147 kB 3.8 MB/s \n\u001B[?25hCollecting chardet<5,>=3.0.2\n  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)\n\u001B[K     |████████████████████████████████| 178 kB 3.9 MB/s ta 0:00:01\n\u001B[?25hCollecting idna<3,>=2.5\n  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)\n\u001B[K     |████████████████████████████████| 58 kB 3.3 MB/s \n\u001B[?25hCollecting urllib3<1.27,>=1.21.1\n  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)\n\u001B[K     |████████████████████████████████| 136 kB 4.2 MB/s \n\u001B[?25hInstalling collected packages: urllib3, idna, chardet, certifi, requests\n\u001B[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\nmoto 1.3.14 requires idna<2.9,>=2.5, but you have idna 2.10 which is incompatible.\nkaggle 1.5.8 requires urllib3<1.25,>=1.21.1, but you have urllib3 1.26.2 which is incompatible.\ncloud-ml 0.0.1 requires requests<=2.25.0,>=2.22.0, but you have requests 2.25.1 which is incompatible.\nbotocore 1.15.49 requires urllib3<1.26,>=1.20; python_version != \"3.4\", but you have urllib3 1.26.2 which is incompatible.\nml-kernel 0.0.1 requires requests<=2.25.0,>=2.22.0, but you have requests 2.25.1 which is incompatible.\u001B[0m\nSuccessfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.2\n\u001B[33mWARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.\u001B[0m\nCollecting requests\n  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)\n\u001B[K     |████████████████████████████████| 61 kB 1.1 MB/s \n\u001B[?25hCollecting certifi>=2017.4.17\n  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)\n\u001B[K     |████████████████████████████████| 147 kB 3.8 MB/s \n\u001B[?25hCollecting chardet<5,>=3.0.2\n  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)\n\u001B[K     |████████████████████████████████| 178 kB 3.9 MB/s \n\u001B[?25hCollecting idna<3,>=2.5\n  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)\n\u001B[K     |████████████████████████████████| 58 kB 3.3 MB/s \n\u001B[?25hCollecting urllib3<1.27,>=1.21.1\n  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)\n\u001B[K     |████████████████████████████████| 136 kB 4.2 MB/s \n\u001B[?25hInstalling collected packages: urllib3, idna, chardet, certifi, requests\n\u001B[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\nmoto 1.3.14 requires idna<2.9,>=2.5, but you have idna 2.10 which is incompatible.\nkaggle 1.5.8 requires urllib3<1.25,>=1.21.1, but you have urllib3 1.26.2 which is incompatible.\ncloud-ml 0.0.1 requires requests<=2.25.0,>=2.22.0, but you have requests 2.25.1 which is incompatible.\nbotocore 1.15.49 requires urllib3<1.26,>=1.20; python_version != \"3.4\", but you have urllib3 1.26.2 which is incompatible.\nml-kernel 0.0.1 requires requests<=2.25.0,>=2.22.0, but you have requests 2.25.1 which is incompatible.\u001B[0m\nSuccessfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.2\n"}],"execution_count":21},{"cell_type":"code","source":"from pathlib import Path\n\npath = Path.cwd()/\"riiidNew\"\nprint(f\"curdir = {Path.cwd()}\")\nimport requests","metadata":{"cellId":"mvh22kgr4tj4k63vksiy","trusted":true},"outputs":[{"output_type":"stream","name":"stdout","text":"curdir = /home/jupyter/work/resources\n"}],"execution_count":23},{"cell_type":"code","source":"url_valid = \"https://yadi.sk/d/7VjrqyxlUedSEA\"\nurl_train = \"https://yadi.sk/d/HuxFMhp6gBUVRw\"\nurl_questions = \"https://yadi.sk/d/Vc9mnbpJctDlGQ\"\nurl_lectures = \"https://yadi.sk/d/1zW7bNdLopP8WA\"\n\n","metadata":{"cellId":"cv5jmby5i3hxtwcd0lxs39","trusted":true},"outputs":[],"execution_count":37},{"cell_type":"code","source":"lectures_csv = \"https://downloader.disk.yandex.ru/disk/e65b49522d1dedc3a2b94986a8553e8a9d5efbef35fe41641fd3e9484ca49fe8/5fdc2be5/YsAzR8NvBSq1wJaOb-hOUcY5DsjwKD-LSQqWxrfAYAcu9v3U4Cx58rfKONIQbK_AX9QBsv76Yk40yNoURddOVA%3D%3D?uid=0&filename=lectures.csv&disposition=attachment&hash=KUpGFDjLJMwm2UqsqtF65Onhoah1Md%2Bq%2BJVR331rRAjvPrTamzjJ5WL%2BHLuSAnoZq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=text%2Fplain&owner_uid=1026434910&fsize=9703&hid=4d4e8c5c4eda7dc2982a7156cd188c5b&media_type=spreadsheet&tknv=v2\"\ncv1_train_pickle_zip_url = \"https://downloader.disk.yandex.ru/disk/4131fa865f891c43b1ac9f0ae8b49fad001b3524cec939a0f6938e7cfeb2b79e/5fdc332b/Sr5cPlY29HlUTAfxRMPjsQr2BWUj4P2vtGcngdenmFPfM0UFvde5sjdpB0Z7RZEEl_WV_Owc-tPRjILMZAXKDw%3D%3D?uid=0&filename=cv1_train.pickle.zip&disposition=attachment&hash=2umV4u1JiHJlMNM5O95R1C7PLVXPDiVYARH5cQLgOLkzNxll4mp9zWaaL8Dmh4OLq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Fzip&owner_uid=1026434910&fsize=1759219769&hid=ed573b8a1333594e5c731d420381ad3b&media_type=compressed&tknv=v2\"\ntrain_feather_url = \"https://downloader.disk.yandex.ru/disk/aa8814843077b2a20f958556937812186cfe97d7079da214015c547802ca7bd4/5fdc49b0/Sr5cPlY29HlUTAfxRMPjsWh2h-4bHw8vX1utrQzCt6hNfYEsp545Rs994RoE2u0z-BL-RizAANRxa5bGL00fqQ%3D%3D?uid=0&filename=train.feather&disposition=attachment&hash=Xa8PXv7nRaDQdfOkcwtwShpe1sVSvgG3O0qbVucmX%2B0fPZGeIDdKToQ6LWUTFHiaq/J6bpmRyOJonT3VoXnDag%3D%3D%3A&limit=0&content_type=application%2Foctet-stream&owner_uid=1026434910&fsize=2087959178&hid=ae45310d34e8c5c55936c673b0084a71&media_type=data&tknv=v2\"\n# wget.download(url_valid, str(path/\"data1\"/\"cv1_valid.pickle.zip\"));\n# wget.download(url_train, str(path/\"data1\"/\"cv1_train.pickle.zip\"));\n# wget.download(url_questions, str(path/\"data1\"/\"questions.csv\"));\n# wget.download(url_lectures, str(path/\"data1\"/\"lectures.csv\"));\nrequest = requests.get(direct_link)","metadata":{"cellId":"j6r9xekfqq437k26ib905","trusted":true},"outputs":[],"execution_count":42},{"cell_type":"code","source":"with open(str(Path.cwd()/'riiidNew'/'data1'/'lectures.csv'), 'wb') as f:\n    f.write(requests.get(lectures_csv))","metadata":{"cellId":"ft3pxz1epon2mptyke5sc3","trusted":true},"outputs":[{"output_type":"stream","name":"stderr","text":"/kernel/lib/python3.7/site-packages/ml_kernel/kernel.py:588: UserWarning: The following variables cannot be serialized: f\n  warnings.warn(message)\n"}],"execution_count":30},{"cell_type":"code","source":"%%time\nwith open(str(Path.cwd()/'riiidNew'/'data1'/'cv1_train.pickle.zip'), 'wb') as f:\n    f.write(requests.get(cv1_train_pickle_zip_url))","metadata":{"cellId":"g6qq15hvu2g0wkotn4a7d","trusted":true},"outputs":[{"output_type":"stream","name":"stderr","text":"/kernel/lib/python3.7/site-packages/ml_kernel/kernel.py:588: UserWarning: The following variables cannot be serialized: f\n  warnings.warn(message)\n"}],"execution_count":40},{"cell_type":"code","source":"%%time\nwith open(str(Path.cwd()/'riiidNew'/'data1'/'train.feather'), 'wb') as f:\n    f.write(requests.get(train_feather_url))","metadata":{"cellId":"jhomijg3ldcd0k06rn825c","trusted":true},"outputs":[{"output_type":"stream","name":"stderr","text":"/kernel/lib/python3.7/site-packages/ml_kernel/kernel.py:588: UserWarning: The following variables cannot be serialized: f\n  warnings.warn(message)\n"}],"execution_count":44},{"cell_type":"code","source":"","metadata":{"cellId":"8scr9bhpeldc9zm35ien3f"},"outputs":[],"execution_count":null}]}